### ISSUE TITLE
TortoiseGit menu items do not show up

### ISSUE THREAD

**Issue by Corderbollie** [RolandoMagico/ContextQuickie2#2]
Hello,

just installed latest version from Marketplace (ContextQuickie2 0.6.2.202101271947).
The menu items for TortoiseGit do not show up in the context menu. Instead two empty lines are shown.
There is no error in the error log. Eclipse Version is 2020-12 (4.18.0).
![grafik](https://user-images.githubusercontent.com/25240926/107351057-72fc2f80-6aca-11eb-9e99-506d0f23840f.png)

![grafik](https://user-images.githubusercontent.com/25240926/107351176-9626df00-6aca-11eb-9087-c58b775d689b.png)

Even with all configuration options enabled the TortoiseGit items do not show up but all others are fine.

**Comment by Corderbollie** [comment]
Hi,
found the solution. The option 'Show overlays and context menu only in explorer' was checked in the tortoisegit settings. I unchecked the option and the menu shows up.
However before I had ContextQuickie (0.13...) installed and this was not a problem.
![grafik](https://user-images.githubusercontent.com/25240926/107360581-6bdb1e80-6ad6-11eb-99d6-bb1a4695d130.png)

**Comment by RolandoMagico** [comment]
Hello @Corderbollie ,
sorry for the delayed response. There is a big difference between ContextQuickie and ContextQuickie2: ContextQuickie is just a hard coded copy of Tortoise Git where all required data is included in the Eclipse plugin. ContextQuickie2 uses the Windows API to retrieve the system context menu data directly from the system.
Looks like Tortoise Git checks if the current process is the explorer if the mentioned option is unchecked. I'll check if I can simulate the explorer environment in this case.

BR
Roland

**Comment by RolandoMagico** [comment]
Update: TortoiseGit is checking if he current process is the system explorer process (https://github.com/TortoiseGit/TortoiseGit/blob/master/src/TortoiseShell/TortoiseStub.cpp, function WantRealVersion)
This check cannot be overwritten by ContextQuickie2
